// Dynamics 365 svcutil extension tool by Kipon ApS, Kjeld Poulsen
// This file is autogenerated. Do not touch the code manually

namespace Kipon.WebResources.Tools.Entities
{
	public partial interface IUnitOfWork
	{
		#region entity repositories
		IRepository<Solution> Solutions { get; }
		IRepository<SolutionComponent> Solutioncomponents { get; }
		IRepository<SystemForm> Systemforms { get; }
		#endregion
	}
}
